package dev.d1s.caching.autoconfiguration

import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.EnableAspectJAutoProxy

@Configuration
@EnableAspectJAutoProxy
public class AspectJAutoProxyAutoConfiguration